### ISSUE TITLE
fzf C-j C-k invalid

### ISSUE THREAD

**Issue by kola-web** [aserowy/tmux.nvim#65]

**Comment by aserowy** [comment]
Can you please elaborate?

Kind regards

**Comment by kola-web** [comment]
Since the plugin uses ctrl j & ctrl k shortcuts in tmux, the default ctrl j & ctrl k shortcuts are invalid when fzf queries files.

**Comment by aserowy** [comment]
i guess, you can change the bindings for ctrl j and k to your needs. Thus, you ll be able to use fzf with defaults or change the bindings in fzf to ctrl n and p (that would be my way i guess).

Kind regards (and sorry for the long absence)
Alexander

**Comment by danielt812** [comment]
I ran into the same issue where C-j and C-k were being intercepted by tmux navigation instead of cycling through items in FZF.

You can fix this by adding the following line to your tmux config file:

`set -g @tmux-nvim-condition "ps -o comm= -t '#{pane_tty}' | grep -iqE 'fzf|n?vim'"`

You can also extend the regex to include other TUI apps like LazyGit or LazyDocker:

`set -g @tmux-nvim-condition "ps -o comm= -t '#{pane_tty}' | grep -iqE 'fzf|lazy(git|docker)|n?vim'"`
